### ISSUE TITLE
Heidelberg typo

### ISSUE THREAD

**Issue by Bushjumper** [beyarkay/eskom-calendar#178]
Hi @beyarkay 

I spotted a typo in the naming of the area for 'Heidelberg' (rather than 'Heidelburg'). Please take a look.

Thanks!

**Comment by beyarkay** [comment]
Hi! 

Sorry it took so long, but this issue is fixed by 44d8623404e4207bf355db6ece7e52e8956aaf7a. Unfortunately I can't change the name of the actual calendar (because this will cause everyone who's copied that link to get a broken calendar), but from now on you can search for either version at https://eskomcalendar.co.za and the correct calendar will pop up.

Feel free to re-open if you've got any questions!
