### ISSUE TITLE
Bothasig

### ISSUE THREAD

**Issue by popsru1es** [beyarkay/eskom-calendar#255]
Hi There

Can you please add Bothasig Western Cape Supplied from Escom

Thanking you
Gideon

**Comment by PuffShr1k3** [comment]
Seconding this - please.
Burgundy Estate is on the same grid as Bothasig.
This is apparently on block 14, however none of the calendars in this repo with "14" in the name appear to reflect the correct schedule.
Thank you, devs!

**Comment by beyarkay** [comment]
Hi there, sorry for not giving feedback sooner, but I will try my best to add bothasig to the project.

**Comment by popsru1es** [comment]
No problem thank you

Gideon

**Comment by beyarkay** [comment]
This should be fixed by [a9820dc](https://github.com/beyarkay/eskom-calendar/commit/a9820dcd4bcfbdc34abf09eac1b77d8f36995c4f).

You can now see Bothasig schedules [here](https://eskomcalendar.co.za/ec?calendar=eskom-direct-13-even.ics) or by searching for "bothasig" at https://eskomcalendar.co.za and choosing the first option.

<details>
<summary>A small side note about EskomSePush</summary>

As a temporary side note, it seems that EskomSePush is hallucinating loadshedding schedules for tomorrow, so in the ESP app you'll see Bothasig has "Power off tomorrow 18:00 - 20:30" even though [the official eskom schedule](https://twitter.com/Eskom_SA/status/1639998087786557440) says nothing about loadshedding after 5am tomorrow morning. 

This isn't a problem, since eskom will announce updated schedules later today and eskom-calendar will be updated with those schedules when they become available.
</details>

Feel free to re-open this issue if you feel it wasn't resolved properly or if you have any other questions.

**Comment by popsru1es** [comment]
Thank You Sir you are A Star.

**Comment by beyarkay** [comment]
Glad I could help! If you like the project, leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated and helps more people discover eskom-calendar

**Comment by popsru1es** [comment]
Star Done
