### ISSUE TITLE
Missing schedule for Eastern-Cape East London (Nahoon Valley)

### ISSUE THREAD

**Issue by travismailsa** [beyarkay/eskom-calendar#271]
There is no ICS for Eastern-Cape East London

**Comment by travismailsa** [comment]
Specifically looking for block 10, Nahoon Valley to add to my HomeAssistant

**Comment by beyarkay** [comment]
Hi there, 

Thanks for reaching out, I will look into adding that area in the near future.

**Comment by beyarkay** [comment]
Hi @travismailsa, this should be fixed by 4f6ab70 and 30d0265a2a93bc985e1f873ac124bf982c13ce2a, and the calendars should be available on eskomcalendar.co.za in about 5 minutes (once [this workflow build](https://github.com/beyarkay/eskom-calendar/actions/runs/4590718230) has completed and shows a green checkmark).

**Comment by beyarkay** [comment]
Here you go!: https://eskomcalendar.co.za/ec?calendar=buffalo-city-block-10.ics if you click that link you'll get the calendar for Nahoon valley. Please feel free to re-open this issue if something looks wrong.

As a final note, (and if you like the project), leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated, as this helps more people discover eskom-calendar

**Comment by travismailsa** [comment]
Thanks mate,

much appreciated. Will go ahead and leave a like :)
