### ISSUE TITLE
Allow for Alternative URL sources or update documentation to mention alternatives are allowed

### ISSUE THREAD

**Issue by Dauntless1121** [beyarkay/eskom-calendar#311]
Eskom's twitter account has been lax to update their statuses directly however news sources are quoting them as having said:

_Stage 2 load-shedding will be implemented from 05:00 until 16:00 on Wednesday, after which stage 3 will run until 05:00 on Thursday.
“This pattern will be repeated until further notice,” Eskom stated._

https://mybroadband.co.za/news/energy/484717-eskom-reveals-load-shedding-schedule-for-rest-of-the-week-including-extended-power-cut-break.html

I haven't tested if editing the yml and changing to a different site is accepted or not,but either the code or documentation should probably allow it in this instance

**Comment by beyarkay** [comment]
Hi there, sorry for the late reply, but editing the yaml to a non-twitter source is permitted.

However, I would be a bit hesitant to approve a pull request that mentioned a secondary website (ie, not the @Eskom_SA twitter account, or another municipality's account) because it's tricky to guarantee that it is accurate. But if it looked legit, then all would be good 👍 

Hope that clarifies things, and feel free to re-open this issue or leave a comment if you've got questions.
