### ISSUE TITLE
Nelson Mandela Bay missing (& solution)

### ISSUE THREAD

**Issue by xander-indsigt** [beyarkay/eskom-calendar#391]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
I think you guys are missing Nelson Mandela Bay municipality's data. Thanks for the repo it's great! I am busy automating the area and schedules information for this municipality, the area is not in the YAML format. Let me know if you want a copy of the code.

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Google

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by beyarkay** [comment]
Hey Xander, thanks for opening the issue!

Nelson Mandela Bay is a known problem because (as far as I can tell, I don't live there) it seems like there's a [19-day cycle](https://www.nelsonmandelabay.gov.za/page/loadshedding) which gets updated every few months, and is only available via a [a PDF](https://www.nelsonmandelabay.gov.za/documentslist?searchtext=&categoryid=58) that (as far as I can tell) will be outdated in 2 months. This makes it slightly painful to add into the project, although definitely not impossible!

If you're working on getting the schedule information, that's fantastic! Here's some information which will be helpful:

1. I did a rewrite of the main code base a while ago, so the source code is very ready for a 19-day cycle. This means that there should be no source code changes required to get NMB up and running.
2. Each area schedule needs to have a CSV file in [`generated/`](https://github.com/beyarkay/eskom-calendar/tree/main/generated) which should have headers like: `day_of_19_day_cycle,start_time,finsh_time,stage`, where `day_of_19_day_cycle` should be a value in `1, 2, 3, ..., 17, 18, 19`.
3. Each area also needs to be added to `area_metadata.yaml`, but that's a different task that I'm happy to help with when the time comes.


Feel free to ask any questions, and if you have any work in progress please feel free to post a link here (:

**Comment by beyarkay** [comment]
This has been fixed by 1074197, You can (finally) search for them in the website (: Let me know if you see any issues (but they should all be correct)
