### ISSUE TITLE
Website incorrectly shows events <=30m long

### ISSUE THREAD

**Issue by Ohwelt** [beyarkay/eskom-calendar#444]
Hi Boyd,
https://eskomcalendar.co.za/ec?calendar=city-power-2.ics
shows load shedding from 16:00-16:30 pm for Parkhurst. There was no load shedding at that time.
Also other websites like 
https://www.ourpower.co.za/areas/jhb-city-power/parkhurst
show no load shedding at that time. 

Am I using the wrong location ID for Parkhurst or is it a bug?
Thanks

**Comment by beyarkay** [comment]
Hi there,

That does seem like the correct calendar for parkhurst. This is due to a bug in the website, however I am in the process of rewriting the website to make it a *lot* nicer. I'm afraid I don't have the time to make a temporary fix to the old website while I'm also making changes to the new website, so I'm going to close this issue.

Apologies for not being able to properly resolve this ):
