### ISSUE TITLE
Google Calendar - no new entries, and also items disappear!

### ISSUE THREAD

**Issue by drmzk** [beyarkay/eskom-calendar#473]
Thanks for the AWESOME tool!

When I add by URL to my Google Calendar, I get a lot of upcoming load shedding entries. However, they sometimes disappear (in future days, I don't mean the ones which have already happened). Furthermore, the calendar doesn't seem to populate new items as time goes on. In other words, when I load the calendar by URL, it populates about 3 or 4 days ahead. After those 3 or 4 days are over, no new items appear. I then delete the calendar URL and add it again, then the new ones populate. As I mentioned, sometimes they disappear before the few days are up, too.

I am using Google Calendar stock app on my Android phone. I also use Sectograph (check it out!) but it is just a piggyback app on top of Google Calendar.

All the best! Hope there's a solution; this could change my life!

Gareth

**Comment by beyarkay** [comment]
Hey! Thanks for the feedback.

Sounds like there are two things happening at once here:

1. Eskom being unpredictable. Over the past few days, Eskom has repeatedly only released less than a day's schedules at a time, so this would cause you to only see a little bit of loadshedding in your calendar (since there literally isnt any more information). Unfortunately there's nothing to be done about this

2. Google calendar being unpredictable (and this one we can fix (kinda)). Unfortunately, google calendar has a known issue where it updates it's subscriptions at an unknown but slow rate. Somewhere around once every 12 to 24 hours. This causes issues when Eskom updates their schedules more frequently. There is a solution, but it involves setting up a script with Google Apps Script: https://stackoverflow.com/a/58860643/14555505 and after that, it works really well.


Apologies that there's not an easy solution here, I've tried to figure out something better but have struggled.

Let me know if this helps, or if I've misunderstood your questions. I'll close this in a few days if I haven't heard anything.

Boyd

**Comment by drmzk** [comment]
Thanks man!

That totally solved it. I wonder whether there may some future for partners between the two projects...

For example, using the script, I can set colours for different ESKOM zones which automatically appear in my calendar. 

In my opinion, every municipality in the country should make a publicly available shared calendar for all of it's zones using these 2 brilliant pieces software. 

Hats off to you! I appreciate your work very much. I wish you a rewarding and interesting career! I'm also a CS graduate, actually! (Totally different - I write firmware for embedded devices...)

Cheers!

**Comment by beyarkay** [comment]
Thanks for the compliment! I dabble a bit with robotics, but nothing crazy. Glad you like the calendar!
