### ISSUE TITLE
Missing area: Gauteng Emfuleni Area A16

### ISSUE THREAD

**Issue by joubertt** [beyarkay/eskom-calendar#474]
Hi, 

Can you please add Gauteng Emfuleni Area A16 to your schedule? 

Thanks!

**Comment by beyarkay** [comment]
Hi, thanks for raising the issue.

Emfuleni is in the pipeline to be added, I've just busy with personal work at the moment. I'll send a message here when it is added.

Can I ask how you heard about eskom-calendar?

**Comment by joubertt** [comment]
Thank you sir, much appreciated!

I use Solar Assistant and they recently added your calendar to their software to better manage battery levels when load shedding is expected.

**Comment by beyarkay** [comment]
Okay cool! I'll try add it ASAP.

**Comment by joubertt** [comment]
Thanks. It seems as if all/most of the other Emfuleni areas are there, with only A16 being absent.

Great work so by the way!

**Comment by beyarkay** [comment]
Ah this was easier than I thought, and got fixed by 0507cdf. You can now search for `emfuleni area a16` and the correct schedule will appear. Not sure why only a16 was missing.

![Screenshot 2023-09-14 at 17 58 10](https://github.com/beyarkay/eskom-calendar/assets/33420535/c8fdc722-cd96-4069-bb5a-4c4af1a7756c)

Here's a link for ya: https://eskomcalendar.co.za/ec?calendar=gauteng-emfuleni-area-a16.ics

Let me know if there are any other issues.

If you like the project, telling a friend about it or leaving a star are great ways to help out (:

**Comment by joubertt** [comment]
Thank you so much!!!
