### ISSUE TITLE
Missing area schedule

### ISSUE THREAD

**Issue by d3xt3r1ty** [beyarkay/eskom-calendar#485]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**

province: gauteng
municipality: city-of-tshwane-metropolitan
city: tshwane
provider: city-of-tshwane
area: **Valhalla - Group 7**

There is a Valhalla - Group 9 already added, but group 7 also exists in Valhalla.  

On ESP the area ID is tshwane-7-valhalla.

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Solar Assistant

**Comment by beyarkay** [comment]
Hey, Thanks for letting me know!

This should be fixed in about 2 minutes, I'll let you know.

**Comment by beyarkay** [comment]
There we go, fixed by https://github.com/beyarkay/eskom-calendar/commit/2f5adc119cba73155cf16ae8e67ab103e6a77fb7

You can go to eskomcalendar.co.za now and search for Valhalla, it will appear for group 7. (You might have to refresh the webpage)


![Screenshot 2023-09-30 at 13 05 41](https://github.com/beyarkay/eskom-calendar/assets/33420535/d683bb2f-80b8-480f-99c2-f9a6e3e054e2)

Let me know if you've got any other questions and I'll try fix them (: If you like the project, then leaving a star/telling a friend is always appreciated
