### ISSUE TITLE
City power schedule change

### ISSUE THREAD

**Issue by GiaCroock** [beyarkay/eskom-calendar#488]
Hi there, just thought I would give you a heads up about schedule changes :)

![Image1](https://github.com/beyarkay/eskom-calendar/assets/88477211/23c64f10-0e7c-477f-9174-b31063ef7261)
![Image2](https://github.com/beyarkay/eskom-calendar/assets/88477211/e56e651c-b6d8-4c83-995e-e5dfd4a43c94)

**Comment by beyarkay** [comment]
Hi!

Thanks so much for the heads up. I'm afraid I won't be able to make these updates in time because I'm head down trying to finish my Master's by 1 December.

If you (or some future traveler) can contribute the changed CSVs I'm more than happy to merge those changes, but I'm afraid I'll only be able to get to it myself around mid-december.

**Comment by beyarkay** [comment]
The lovely @declan-fitzpatrick has contributed updates to the city-power schedules. 

You'll now be able to access the calendars, although the search box on the website will still be out of date until it can be updated (see [the PR](https://github.com/beyarkay/eskom-calendar/pull/489) for details). Even though the search box will be out of date, you can still view the updated calendars if you go directly to the link like https://eskomcalendar.co.za/ec/?calendar=city-power-1.ics).

If you find any mistakes with the schedules, please let me know and I'll see what I can do.

I'll close this issue once the search box in the website has also been updated.

**Comment by beyarkay** [comment]
Fixed by https://github.com/beyarkay/eskom-calendar/pull/491
