### ISSUE TITLE
City Power schedule issue

### ISSUE THREAD

**Issue by Jbenci** [beyarkay/eskom-calendar#67]
Hi there, 

Thank you for a great product. 

It seems there is a discrepancy for city-power-11 or I am doing something wrong. 

If I compare CityPowers schedule, there are four blocks of load shedding for this date, but only one block appears in the calendar. 

https://www.citypower.co.za/customers/Pages/Load_Shedding_Downloads.aspx
![image](https://user-images.githubusercontent.com/7857734/191454315-ba3942bf-9e45-473a-8710-59919a66be63.png)

![image](https://user-images.githubusercontent.com/7857734/191454362-96962e00-f7a2-4362-8b6a-20eb5a8145d1.png)

Is there anything I can do?

**Comment by beyarkay** [comment]
Hey! Thanks for your feedback. Having a look now.

**Comment by beyarkay** [comment]
Should be being fixed now by b5a7fbe. You can watch the build [here](https://github.com/beyarkay/eskom-calendar/actions/runs/3096642216) if you want, but it should finish in about 5 minutes. Once it's finished, your calendar app will pull down the changes.

If you're impatient and your calendar app isn't updating, some calendars allow you to 'force update', otherwise you can delete the old calendar, resubscribe, and then it will be forced to download the new schedule.

**Comment by Jbenci** [comment]
Incredible speed. I can confirm its working. Youre the best. Thank you!

**Comment by beyarkay** [comment]
Yup, it all looks good to me. Thanks for raising the issue! these things are really tricky to spot on my own since I can't monitor every area all the time.


For posterity, here's the machine_friendly.csv curl of city-power-11 now that it's fixed:
```
$ curl -Ls https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv \
    | grep "city-power-11" \
    | grep "2022-09-21"
city-power-11,2022-09-21T02:00:00+02:00,2022-09-21T04:30:00+02:00,5,"https://twitter.com/Eskom_SA/status/1572254543668281344"
city-power-11,2022-09-21T10:00:00+02:00,2022-09-21T12:30:00+02:00,5,"https://twitter.com/Eskom_SA/status/1572254543668281344"
city-power-11,2022-09-21T12:00:00+02:00,2022-09-21T14:30:00+02:00,5,"https://twitter.com/Eskom_SA/status/1572254543668281344"
city-power-11,2022-09-21T18:00:00+02:00,2022-09-21T20:30:00+02:00,5,"https://twitter.com/Eskom_SA/status/1572254543668281344"
```
