### ISSUE TITLE
Missing schedules in Drakenstein, WC (Val de Vie)

### ISSUE THREAD

**Issue by Gideon-ZA** [beyarkay/eskom-calendar#77]
Hi,

I don't see a loadshedding schedule for Paarl. Can you please help?

**Comment by beyarkay** [comment]
Hey! thanks for the feedback.

So this is an annoying issue. The project gets loadshedding schedules from [this website](https://www.eskom.co.za/distribution/customer-service/outages/municipal-loadshedding-schedules/western-cape/) and if you go and open up the `Drakenstein` dropdown box you'll see that Paarl doesn't have a link attached to it, so the scraper wasn't downloading the schedule (because as far as the scraper was concerned, Paarl didn't have a schedule)

It seems like [this PDF](http://www.drakenstein.gov.za/docs/Documents/Stage%201%20-%208%20Load%20Shedding%20Schedule%2023%20January%202018%20REV0%20(2).pdf) (found on [this page](http://www.drakenstein.gov.za/cc/Pages/Key-to-Eskom-load-shedding.aspx)) defines the loadshedding for **Pearl Valley, Val de Vie, Paarl, Wellington, Windmeul, Hermon, Saron & Gouda** although I'd want to double check that this information is correct before adding it all, since [Gouda](https://www.eskom.co.za/distribution/wp-content/uploads/2021/06/Gouda.pdf) and [Wellington](https://www.eskom.co.za/distribution/wp-content/uploads/2021/06/Wellington.pdf) all have PDFs available on the main Eskom webpage for the western cape [here](https://www.eskom.co.za/distribution/customer-service/outages/municipal-loadshedding-schedules/western-cape/).

But don't worry, I will add Paarl (and probably also Pearl Valley, Val de Vie, Wellington, Windmeul, Hermon, Saron & Gouda as well in the process) as soon as I can.

Thanks for letting me know!

**Comment by Gideon-ZA** [comment]
Hi,Thank you very much for the quick response. Yes, I've seen the website is faulty.I can confirm that the load shedding schedule in that pdf is correct for Paarl.Thank you for all your effort.Do you mind letting me know when you add Paarl?Enjoy your weekend. Kind Regards Gideon Cillié 
-------- Original message --------From: Boyd Kane ***@***.***> Date: 2022/09/23  10:12  (GMT+02:00) To: beyarkay/eskom-calendar ***@***.***> Cc: Gideon-ZA ***@***.***>, Author ***@***.***> Subject: Re: [beyarkay/eskom-calendar] No Loadshedding Schedule for Paarl (Issue #77) 
Hey! thanks for the feedback.
So this is an annoying issue. The project gets loadshedding schedules from this website and if you go and open up the Drakenstein dropdown box you'll see that Paarl doesn't have a link attached to it, so the scraper wasn't downloading the schedule (because as far as the scraper was concerned, Paarl didn't have a schedule)
It seems like this PDF (found on this page) defines the loadshedding for Pearl Valley, Val de Vie, Paarl, Wellington, Windmeul, Hermon, Saron & Gouda although I'd want to double check that this information is correct before adding it all, since Gouda and Wellington all have PDFs available on the main Eskom webpage for the western cape here.
But don't worry, I will add Paarl (and probably also Pearl Valley, Val de Vie, Wellington, Windmeul, Hermon, Saron & Gouda as well in the process) as soon as I can.
Thanks for letting me know!

**Comment by beyarkay** [comment]
Hi! Sure thing, hopefully I'll be able to get to it this weekend, but I've got an assignment due Tuesday so we'll have to see how it goes. I'll let you know when it's added.

**Comment by Gideon-ZA** [comment]
Hi,

 

Do perhaps know when Paarl will be added to the load shedding calendar on the website?

 

Vriendelike Groete/Kind Regards

Gideon Cillié

**Comment by robertstheari** [comment]
Hi,
This is an awesome piece of work - well done!
I saw the last comms on Paarl schedules was a while back, were there any updates since then perhaps?
Thanks and keep up the good work!

**Comment by beyarkay** [comment]
I'm happy to say that Paarl (and many other areas) have been added. You can get the schedules by searching for paarl at https://eskomcalendar.co.za/ec or by following the below links:

- Paarl: https://eskomcalendar.co.za/ec?calendar=eskom-direct-8-even.ics
- Paarl outlying: https://eskomcalendar.co.za/ec?calendar=eskom-direct-16-odd.ics
- Windmill: https://eskomcalendar.co.za/ec?calendar=eskom-direct-10-odd.ics
- Some of the other areas are available at eskomcalendar.co.za, however there are multiple schedules for them so I'm not sure which ones you'll want.

I'm still not sure about Val de Vie though. I'll keep the issue open until I can resolve that.

**Comment by robertstheari** [comment]
AWESOME! Thank you so much!!
