### ISSUE TITLE
Macassar - Western Cape area missing

### ISSUE THREAD

**Issue by JPvanderMerwe** [beyarkay/eskom-calendar#92]
Hi @beyarkay , as previously discussed I think your open source work is great and lots of work has been put into the project. Could I ask that you add the Macassar area please as I stay in Somerset West but our schedule falls under this area. If you need help with adding areas or anything else in the future I don't mind helping with the right guidance. Keep up the good work.

**Comment by beyarkay** [comment]
Hey! thanks for letting me know about this. I have a hunch that Macassar also falls into an existing bug with a few other areas, so this is high priority but I'm under a bit of time pressure at the moment with Uni work. Hopefully I'll be able to get to this on the weekend.

If you'd like to contribute, that would be great! Adding a new area basically consists of committing a CSV file that's got the headers `date_of_month,start_time,finsh_time,stage` to the `generated/` directory. [Here's](https://github.com/beyarkay/eskom-calendar/blob/main/generated/western-cape-stellenbosch.csv) an example of what the stellenbosch CSV looks like:

```
date_of_month,start_time,finsh_time,stage
1,02:00,04:30,1
1,02:00,04:30,2
1,02:00,04:30,3
1,02:00,04:30,4
1,02:00,06:30,5
1,02:00,06:30,6
1,02:00,06:30,7
...
```

Note that `finsh` doesn't have the second `i`, so that it lines up with `start`. The CSV should be sorted by `date_of_month` first, then `start_time`, and then `stage`.


Once file is committed to `main`, it'll automatically get built by the `publish` github action and the calendars for the new area will become available on the releases page.

So far I've got python scripts which download loadshedding PDFs from the internet and convert them to CSVs just in case things change in the future, and so I don't have to manually enter all the numbers myself (see `src/parse_*.py`). But it's quite a pain to wrangle the PDFs into that format, so I won't make that a requirement if you want to try get Macassar done yourself.

But like I said, hopefully I'll be able to sort out Macassar and the other missing areas this weekend all in one fell swoop.

**Comment by JPvanderMerwe** [comment]
Awesome sounds good, will definitely take a look at everything and be in contact as I am also quite busy with work myself, but this a fun project. Anyways all the best with that Uni work, and thanks for the guidance and again your time and effort.

**Comment by beyarkay** [comment]
Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Macassar: https://eskomcalendar.co.za/ec?calendar=eskom-direct-8-odd.ics

Hope that helps! Feel free to open the issue again if you have any questions
